# Generated by Django 2.0.1 on 2018-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LongToShortURL', '0002_longtoshort_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtoshort',
            name='counter',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
