# Generated by Django 2.0.1 on 2018-06-29 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LongToShortURL', '0003_auto_20180626_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='long_url',
            field=models.URLField(max_length=800),
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='short_url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
