# Generated by Django 2.0.1 on 2018-06-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LongToShortURL', '0008_auto_20180629_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtoshort',
            options={'verbose_name': 'shortenedURL'},
        ),
        migrations.AddField(
            model_name='longtoshort',
            name='name',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
