# Generated by Django 2.0.1 on 2018-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LongToShortURL', '0009_auto_20180629_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtoshort',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
